import type { ProjectInputs } from "./types.ts";

export type Preset = {
  id: string;
  name: string;
  place: string;
  blurb: string;
  inputs: ProjectInputs;
};

const base: Pick<ProjectInputs, "floorHeight" | "balconyDepth" | "costPerM2" | "facade" | "aptsPerFloor" | "floorPrograms" | "massing" | "roofType" | "semiBasement" | "garageDoor" | "basementLevels" | "parkingTarget" | "rampSide" | "basementStorage" | "basementHeight"> = {
  floorHeight: 3,
  balconyDepth: 1.6,
  costPerM2: 1650,
  facade: "cream",
  aptsPerFloor: 2,
  floorPrograms: {},
  massing: "coverage",
  roofType: "flat",
  semiBasement: false,
  garageDoor: true,
  basementLevels: 1,
  parkingTarget: 0,
  rampSide: "left",
  basementStorage: true,
  basementHeight: 2.8,
};

export const DEFAULT_INPUTS: ProjectInputs = {
  ...base,
  plotWidth: 12,
  plotDepth: 22,
  far: 2.4,
  coverage: 0.7,
  maxHeight: 21,
  system: "continuous",
  frontSetback: 0,
  sideSetback: 0,
  rearSetback: 3,
  pilotis: true,
  basement: true,
  facade: "cream",
};

export const PRESETS: Preset[] = [
  {
    id: "kypseli",
    name: "Αστικό κέντρο",
    place: "Κυψέλη / Παγκράτι",
    blurb: "Συνεχές σύστημα, κλασική πολυκατοικία με πιλοτή.",
    inputs: { ...DEFAULT_INPUTS },
  },
  {
    id: "kolonaki",
    name: "Υψηλή δόμηση",
    place: "Κέντρο / Κολωνάκι",
    blurb: "Μεγάλος Σ.Δ., καταστήματα στο ισόγειο, ψηλό κτίριο.",
    inputs: {
      ...base,
      plotWidth: 10,
      plotDepth: 18,
      far: 3.6,
      coverage: 0.7,
      maxHeight: 27,
      system: "continuous",
      frontSetback: 0,
      sideSetback: 0,
      rearSetback: 2.5,
      pilotis: false,
      basement: true,
      aptsPerFloor: 2,
      facade: "white",
      balconyDepth: 1.4,
    },
  },
  {
    id: "glyfada",
    name: "Γενική κατοικία",
    place: "Γλυφάδα / Χαλάνδρι",
    blurb: "Πανταχόθεν ελεύθερο, προκήπιο, μεσαίο ύψος.",
    inputs: {
      ...base,
      plotWidth: 16,
      plotDepth: 28,
      far: 1.2,
      coverage: 0.6,
      maxHeight: 14,
      system: "detached",
      frontSetback: 4,
      sideSetback: 2.5,
      rearSetback: 4,
      pilotis: true,
      basement: true,
      aptsPerFloor: 2,
      facade: "sand",
      balconyDepth: 1.8,
    },
  },
  {
    id: "suburb",
    name: "Αμιγής κατοικία",
    place: "Προάστιο",
    blurb: "Χαμηλός Σ.Δ., κήπος, δύο-τρεις όροφοι.",
    inputs: {
      ...base,
      plotWidth: 20,
      plotDepth: 30,
      far: 0.8,
      coverage: 0.4,
      maxHeight: 11,
      system: "detached",
      frontSetback: 4,
      sideSetback: 3,
      rearSetback: 5,
      pilotis: false,
      basement: false,
      garageDoor: false,
      aptsPerFloor: 1,
      facade: "ochre",
      roofType: "pitched",
      balconyDepth: 1.5,
      massing: "coverage",
    },
  },
  {
    id: "outplan",
    name: "Εκτός σχεδίου",
    place: "Μεγάλο οικόπεδο",
    blurb: "Σ.Δ. 0,2 — χαμηλή κατοικία σε ευρύ οικόπεδο.",
    inputs: {
      ...base,
      plotWidth: 40,
      plotDepth: 50,
      far: 0.2,
      coverage: 0.2,
      maxHeight: 7.5,
      system: "detached",
      frontSetback: 10,
      sideSetback: 7.5,
      rearSetback: 10,
      pilotis: false,
      basement: false,
      garageDoor: false,
      aptsPerFloor: 1,
      facade: "sand",
      roofType: "pitched",
      balconyDepth: 1.8,
      costPerM2: 1850,
    },
  },
];
